### ISSUE TITLE
Why not shuffle validation data during search

### ISSUE THREAD

**Issue by ultmaster** [megvii-model/SinglePathOneShot#4]
Hi. Thanks for this great repo.

https://github.com/megvii-model/SinglePathOneShot/blob/36eed6cf083497ffa9cfe7b8da25bb0b6ba5a452/src/Search/imagenet_dataset.py#L94

This seems to have produced very unstable validation results.

**Comment by ZichaoGuo** [comment]
The BN statistics will be calculated by the training data before validation, and all the image in validation data will be tested. So shuffle or not doesn't matter to the results.

**Comment by ultmaster** [comment]
Sorry. I thought that only a subset of validation data will be tested on.
