### ISSUE TITLE
Use BGR tensor in data preprocessing

### ISSUE THREAD

**Issue by ultmaster** [megvii-model/SinglePathOneShot#5]
Hi. Thanks for this great repo.

I'm interested in why you did convert to BGR tensor intentionally and keep the values between 0 - 255 instead of normalization (div 255, minus mean, div std) as usual.

Related code:

https://github.com/megvii-model/SinglePathOneShot/blob/36eed6cf083497ffa9cfe7b8da25bb0b6ba5a452/src/Supernet/train.py#L37

**Comment by ZichaoGuo** [comment]
Just in order to keep the same as that in our own DL framework.

**Comment by ultmaster** [comment]
Thanks for response.
